spring:
  application:
    name: gateway
  port: 8059
  cloud:
    discovery:
      enabled: false
    gateway:
      discovery:
        locator:
          enabled: true
        lowerCaseServiceId: true
#  slueth:
#    sampler:
#      probability: 1.00
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka